[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Commands passed to pip install before extension gets enabled. Can also contain flags, like `--upgrade`, `--no--index`, etc.
# Refer to: https://pip.pypa.io/en/stable/reference/requirements-file-format/
# requirements = [
#     "torch==1.13.1+cpu",
#     "diffusers==0.10.2",
#     "transformers",
#     "scipy",
#     "ftfy",
#     "accelerate"
# ]

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA", "Suriya"]

# The title and description fields are primarily for displaying extension info in UI
title = "suriya avatar generator"
description="Python extension which uses stable diffusion to create artistic 3D avatars"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/previewStable.jpg"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import suriya.avatar.generator".
[[python.module]]
name = "suriya.avatar.generator"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
